using System;
using System.Collections.Generic;
using UnityEngine;

namespace HotPatata
{
    /// <summary>The KayKit piece families a <see cref="KitSkin"/> tiles a box with (ARCHITECTURE §25.1).</summary>
    public enum KitShape
    {
        Platform,   // platform_WxDxH: a coloured top over grey sides (floors, steps, movers)
        Barrier,    // barrier_Wx1xH: rounded blocks one metre deep (walls, posts, bars, frames)
        Arrow,      // platform_arrow: a platform with a white chevron on top (belts, slides)
        Pipe,       // pipe_straight: a tube along the box's Y axis (tubes, barrels)
        Floor,      // timber floor panels, Platformer pack
        Pillar,     // structural posts
        Strut,      // open steel trusses
        BevelBox,   // a chamfered box generated by KitSkin (no palette piece): the industrial look, ARCHITECTURE §25.2
        RoughBox,   // a rough rock slab generated by NatureShapes (no palette piece): the nature look, ARCHITECTURE §25.3
        Logs,       // a bundle of logs generated by NatureShapes: rafts, palisades, rams, posts
        Planks,     // a planked box generated by NatureShapes: bridges, boardwalks, decks, lifts
        Boulder,    // a rounded boulder filling its box (NatureShapes): stepping stones, rocks, pillars
        Skirt,      // the rock mass under a raised slab (NatureShapes, decoration only): it widens with depth
        Crag        // a rock spur against a cliff (NatureShapes): deeply rounded, domed, never walked on
    }

    /// <summary>KayKit colour variants. Each role of the course has one (ARCHITECTURE §25.1).</summary>
    public enum KitColor { Blue, Green, Red, Yellow, Neutral }

    /// <summary>
    /// The KayKit meshes <see cref="KitSkin"/> builds with, by shape and colour, and the materials that draw them.
    /// Generated by <c>KayKitKitBuilder</c> from the imported pack; never edit it by hand.
    /// </summary>
    [CreateAssetMenu(menuName = "HotPatata/Kit Palette")]
    public class KitPalette : ScriptableObject
    {
        [Serializable]
        public struct Piece
        {
            public KitShape shape;
            public KitColor color;
            public Mesh mesh;
        }

        [SerializeField] Piece[] pieces = Array.Empty<Piece>();

        readonly Dictionary<(KitShape, KitColor), List<Mesh>> lookup = new Dictionary<(KitShape, KitColor), List<Mesh>>();

        public IReadOnlyList<Piece> Pieces => pieces;

        public void SetPieces(Piece[] value)
        {
            pieces = value ?? Array.Empty<Piece>();
            lookup.Clear();
        }

        void OnEnable() => lookup.Clear();

        /// <summary>The meshes of one family in one colour; a colour the pack lacks falls back to neutral, then to any.</summary>
        public IReadOnlyList<Mesh> Meshes(KitShape shape, KitColor color)
        {
            if (lookup.Count == 0)
                foreach (var p in pieces)
                {
                    if (p.mesh == null) continue;
                    if (!lookup.TryGetValue((p.shape, p.color), out var list)) lookup[(p.shape, p.color)] = list = new List<Mesh>();
                    list.Add(p.mesh);
                }
            if (lookup.TryGetValue((shape, color), out var found)) return found;
            if (lookup.TryGetValue((shape, KitColor.Neutral), out found)) return found;
            foreach (var kv in lookup)
                if (kv.Key.Item1 == shape) return kv.Value;
            return Array.Empty<Mesh>();
        }
    }
}
